// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"time"

	"github.com/google/uuid"
)

type PessoaFisica struct {
	ID           uuid.UUID `json:"id"`
	RendaMensal  float64   `json:"renda_mensal"`
	Idade        int32     `json:"idade"`
	NomeCompleto string    `json:"nome_completo"`
	Celular      string    `json:"celular"`
	Email        string    `json:"email"`
	Categoria    string    `json:"categoria"`
	Saldo        float64   `json:"saldo"`
	UserID       uuid.UUID `json:"user_id"`
}

type PessoaJuridica struct {
	ID               uuid.UUID `json:"id"`
	Faturamento      float64   `json:"faturamento"`
	Idade            int32     `json:"idade"`
	NomeFantasia     string    `json:"nome_fantasia"`
	Celular          string    `json:"celular"`
	EmailCorporativo string    `json:"email_corporativo"`
	Categoria        string    `json:"categoria"`
	Saldo            float64   `json:"saldo"`
	UserID           uuid.UUID `json:"user_id"`
}

type Session struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	UserName     string    `json:"user_name"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
