// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pessoa_juridica.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const addSaldoPessoaJuridica = `-- name: AddSaldoPessoaJuridica :one
UPDATE pessoa_juridica
SET saldo = saldo + $2
WHERE id = $1
RETURNING id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo, user_id
`

type AddSaldoPessoaJuridicaParams struct {
	ID    uuid.UUID `json:"id"`
	Saldo float64   `json:"saldo"`
}

func (q *Queries) AddSaldoPessoaJuridica(ctx context.Context, arg AddSaldoPessoaJuridicaParams) (PessoaJuridica, error) {
	row := q.db.QueryRow(ctx, addSaldoPessoaJuridica, arg.ID, arg.Saldo)
	var i PessoaJuridica
	err := row.Scan(
		&i.ID,
		&i.Faturamento,
		&i.Idade,
		&i.NomeFantasia,
		&i.Celular,
		&i.EmailCorporativo,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}

const createPessoaJuridica = `-- name: CreatePessoaJuridica :one
INSERT INTO pessoa_juridica (
    faturamento,
    idade,
    nome_fantasia,
    celular,
    email_corporativo,
    categoria,
    saldo,
    user_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo, user_id
`

type CreatePessoaJuridicaParams struct {
	Faturamento      float64   `json:"faturamento"`
	Idade            int32     `json:"idade"`
	NomeFantasia     string    `json:"nome_fantasia"`
	Celular          string    `json:"celular"`
	EmailCorporativo string    `json:"email_corporativo"`
	Categoria        string    `json:"categoria"`
	Saldo            float64   `json:"saldo"`
	UserID           uuid.UUID `json:"user_id"`
}

func (q *Queries) CreatePessoaJuridica(ctx context.Context, arg CreatePessoaJuridicaParams) (PessoaJuridica, error) {
	row := q.db.QueryRow(ctx, createPessoaJuridica,
		arg.Faturamento,
		arg.Idade,
		arg.NomeFantasia,
		arg.Celular,
		arg.EmailCorporativo,
		arg.Categoria,
		arg.Saldo,
		arg.UserID,
	)
	var i PessoaJuridica
	err := row.Scan(
		&i.ID,
		&i.Faturamento,
		&i.Idade,
		&i.NomeFantasia,
		&i.Celular,
		&i.EmailCorporativo,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}

const deletePessoaJuridica = `-- name: DeletePessoaJuridica :exec
DELETE FROM pessoa_juridica
WHERE id = $1
`

func (q *Queries) DeletePessoaJuridica(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePessoaJuridica, id)
	return err
}

const getPessoaJuridica = `-- name: GetPessoaJuridica :one
SELECT id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo, user_id
FROM pessoa_juridica
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPessoaJuridica(ctx context.Context, id uuid.UUID) (PessoaJuridica, error) {
	row := q.db.QueryRow(ctx, getPessoaJuridica, id)
	var i PessoaJuridica
	err := row.Scan(
		&i.ID,
		&i.Faturamento,
		&i.Idade,
		&i.NomeFantasia,
		&i.Celular,
		&i.EmailCorporativo,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}

const getPessoaJuridicaByEmail = `-- name: GetPessoaJuridicaByEmail :one
SELECT id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo, user_id
FROM pessoa_juridica
WHERE email_corporativo = $1
LIMIT 1
`

func (q *Queries) GetPessoaJuridicaByEmail(ctx context.Context, emailCorporativo string) (PessoaJuridica, error) {
	row := q.db.QueryRow(ctx, getPessoaJuridicaByEmail, emailCorporativo)
	var i PessoaJuridica
	err := row.Scan(
		&i.ID,
		&i.Faturamento,
		&i.Idade,
		&i.NomeFantasia,
		&i.Celular,
		&i.EmailCorporativo,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}

const getPessoaJuridicaByUserID = `-- name: GetPessoaJuridicaByUserID :one
SELECT id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo, user_id
FROM pessoa_juridica
WHERE id = $1
  AND user_id = $2
LIMIT 1
`

type GetPessoaJuridicaByUserIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPessoaJuridicaByUserID(ctx context.Context, arg GetPessoaJuridicaByUserIDParams) (PessoaJuridica, error) {
	row := q.db.QueryRow(ctx, getPessoaJuridicaByUserID, arg.ID, arg.UserID)
	var i PessoaJuridica
	err := row.Scan(
		&i.ID,
		&i.Faturamento,
		&i.Idade,
		&i.NomeFantasia,
		&i.Celular,
		&i.EmailCorporativo,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}

const getPessoaJuridicaByUserId = `-- name: GetPessoaJuridicaByUserId :many
SELECT id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo, user_id
FROM pessoa_juridica
WHERE user_id = $1
`

func (q *Queries) GetPessoaJuridicaByUserId(ctx context.Context, userID uuid.UUID) ([]PessoaJuridica, error) {
	rows, err := q.db.Query(ctx, getPessoaJuridicaByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PessoaJuridica
	for rows.Next() {
		var i PessoaJuridica
		if err := rows.Scan(
			&i.ID,
			&i.Faturamento,
			&i.Idade,
			&i.NomeFantasia,
			&i.Celular,
			&i.EmailCorporativo,
			&i.Categoria,
			&i.Saldo,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPessoasJuridicas = `-- name: ListPessoasJuridicas :many
SELECT id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo, user_id
FROM pessoa_juridica
ORDER BY nome_fantasia
LIMIT $1
OFFSET $2
`

type ListPessoasJuridicasParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPessoasJuridicas(ctx context.Context, arg ListPessoasJuridicasParams) ([]PessoaJuridica, error) {
	rows, err := q.db.Query(ctx, listPessoasJuridicas, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PessoaJuridica
	for rows.Next() {
		var i PessoaJuridica
		if err := rows.Scan(
			&i.ID,
			&i.Faturamento,
			&i.Idade,
			&i.NomeFantasia,
			&i.Celular,
			&i.EmailCorporativo,
			&i.Categoria,
			&i.Saldo,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPessoasJuridicasByUserID = `-- name: ListPessoasJuridicasByUserID :many
SELECT id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo, user_id
FROM pessoa_juridica
WHERE user_id = $1
ORDER BY nome_fantasia
LIMIT $2
OFFSET $3
`

type ListPessoasJuridicasByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListPessoasJuridicasByUserID(ctx context.Context, arg ListPessoasJuridicasByUserIDParams) ([]PessoaJuridica, error) {
	rows, err := q.db.Query(ctx, listPessoasJuridicasByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PessoaJuridica
	for rows.Next() {
		var i PessoaJuridica
		if err := rows.Scan(
			&i.ID,
			&i.Faturamento,
			&i.Idade,
			&i.NomeFantasia,
			&i.Celular,
			&i.EmailCorporativo,
			&i.Categoria,
			&i.Saldo,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSaldoPessoaJuridica = `-- name: RemoveSaldoPessoaJuridica :one
UPDATE pessoa_juridica
SET saldo = saldo - $2
WHERE id = $1
  AND saldo >= $2
RETURNING id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo, user_id
`

type RemoveSaldoPessoaJuridicaParams struct {
	ID    uuid.UUID `json:"id"`
	Saldo float64   `json:"saldo"`
}

func (q *Queries) RemoveSaldoPessoaJuridica(ctx context.Context, arg RemoveSaldoPessoaJuridicaParams) (PessoaJuridica, error) {
	row := q.db.QueryRow(ctx, removeSaldoPessoaJuridica, arg.ID, arg.Saldo)
	var i PessoaJuridica
	err := row.Scan(
		&i.ID,
		&i.Faturamento,
		&i.Idade,
		&i.NomeFantasia,
		&i.Celular,
		&i.EmailCorporativo,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}

const updatePessoaJuridica = `-- name: UpdatePessoaJuridica :one
UPDATE pessoa_juridica
SET
    faturamento = $2,
    idade = $3,
    nome_fantasia = $4,
    celular = $5,
    email_corporativo = $6,
    categoria = $7,
    saldo = $8
WHERE id = $1
RETURNING id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo, user_id
`

type UpdatePessoaJuridicaParams struct {
	ID               uuid.UUID `json:"id"`
	Faturamento      float64   `json:"faturamento"`
	Idade            int32     `json:"idade"`
	NomeFantasia     string    `json:"nome_fantasia"`
	Celular          string    `json:"celular"`
	EmailCorporativo string    `json:"email_corporativo"`
	Categoria        string    `json:"categoria"`
	Saldo            float64   `json:"saldo"`
}

func (q *Queries) UpdatePessoaJuridica(ctx context.Context, arg UpdatePessoaJuridicaParams) (PessoaJuridica, error) {
	row := q.db.QueryRow(ctx, updatePessoaJuridica,
		arg.ID,
		arg.Faturamento,
		arg.Idade,
		arg.NomeFantasia,
		arg.Celular,
		arg.EmailCorporativo,
		arg.Categoria,
		arg.Saldo,
	)
	var i PessoaJuridica
	err := row.Scan(
		&i.ID,
		&i.Faturamento,
		&i.Idade,
		&i.NomeFantasia,
		&i.Celular,
		&i.EmailCorporativo,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}

const updateSaldoPessoaJuridica = `-- name: UpdateSaldoPessoaJuridica :one
UPDATE pessoa_juridica
SET saldo = $2
WHERE id = $1
RETURNING id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo, user_id
`

type UpdateSaldoPessoaJuridicaParams struct {
	ID    uuid.UUID `json:"id"`
	Saldo float64   `json:"saldo"`
}

func (q *Queries) UpdateSaldoPessoaJuridica(ctx context.Context, arg UpdateSaldoPessoaJuridicaParams) (PessoaJuridica, error) {
	row := q.db.QueryRow(ctx, updateSaldoPessoaJuridica, arg.ID, arg.Saldo)
	var i PessoaJuridica
	err := row.Scan(
		&i.ID,
		&i.Faturamento,
		&i.Idade,
		&i.NomeFantasia,
		&i.Celular,
		&i.EmailCorporativo,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}
