// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pessoa_fisica.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createPessoaFisica = `-- name: CreatePessoaFisica :one
INSERT INTO pessoa_fisica (
    renda_mensal,
    idade,
    nome_completo,
    celular,
    email,
    categoria,
    saldo,
    user_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, renda_mensal, idade, nome_completo, celular, email, categoria, saldo, user_id
`

type CreatePessoaFisicaParams struct {
	RendaMensal  float64   `json:"renda_mensal"`
	Idade        int32     `json:"idade"`
	NomeCompleto string    `json:"nome_completo"`
	Celular      string    `json:"celular"`
	Email        string    `json:"email"`
	Categoria    string    `json:"categoria"`
	Saldo        float64   `json:"saldo"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) CreatePessoaFisica(ctx context.Context, arg CreatePessoaFisicaParams) (PessoaFisica, error) {
	row := q.db.QueryRow(ctx, createPessoaFisica,
		arg.RendaMensal,
		arg.Idade,
		arg.NomeCompleto,
		arg.Celular,
		arg.Email,
		arg.Categoria,
		arg.Saldo,
		arg.UserID,
	)
	var i PessoaFisica
	err := row.Scan(
		&i.ID,
		&i.RendaMensal,
		&i.Idade,
		&i.NomeCompleto,
		&i.Celular,
		&i.Email,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}

const deletePessoaFisica = `-- name: DeletePessoaFisica :exec
DELETE FROM pessoa_fisica
WHERE id = $1
`

func (q *Queries) DeletePessoaFisica(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePessoaFisica, id)
	return err
}

const getPessoaFisica = `-- name: GetPessoaFisica :one
SELECT id, renda_mensal, idade, nome_completo, celular, email, categoria, saldo, user_id
FROM pessoa_fisica
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPessoaFisica(ctx context.Context, id uuid.UUID) (PessoaFisica, error) {
	row := q.db.QueryRow(ctx, getPessoaFisica, id)
	var i PessoaFisica
	err := row.Scan(
		&i.ID,
		&i.RendaMensal,
		&i.Idade,
		&i.NomeCompleto,
		&i.Celular,
		&i.Email,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}

const getPessoaFisicaByUserId = `-- name: GetPessoaFisicaByUserId :many
SELECT id, renda_mensal, idade, nome_completo, celular, email, categoria, saldo, user_id
FROM pessoa_fisica
WHERE user_id = $1
`

func (q *Queries) GetPessoaFisicaByUserId(ctx context.Context, userID uuid.UUID) ([]PessoaFisica, error) {
	rows, err := q.db.Query(ctx, getPessoaFisicaByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PessoaFisica
	for rows.Next() {
		var i PessoaFisica
		if err := rows.Scan(
			&i.ID,
			&i.RendaMensal,
			&i.Idade,
			&i.NomeCompleto,
			&i.Celular,
			&i.Email,
			&i.Categoria,
			&i.Saldo,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPessoaFisicaByUserIdAndEmail = `-- name: GetPessoaFisicaByUserIdAndEmail :one
SELECT id, renda_mensal, idade, nome_completo, celular, email, categoria, saldo, user_id
FROM pessoa_fisica
WHERE user_id = $1 AND email = $2
LIMIT 1
`

type GetPessoaFisicaByUserIdAndEmailParams struct {
	UserID uuid.UUID `json:"user_id"`
	Email  string    `json:"email"`
}

func (q *Queries) GetPessoaFisicaByUserIdAndEmail(ctx context.Context, arg GetPessoaFisicaByUserIdAndEmailParams) (PessoaFisica, error) {
	row := q.db.QueryRow(ctx, getPessoaFisicaByUserIdAndEmail, arg.UserID, arg.Email)
	var i PessoaFisica
	err := row.Scan(
		&i.ID,
		&i.RendaMensal,
		&i.Idade,
		&i.NomeCompleto,
		&i.Celular,
		&i.Email,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}

const listPessoasFisicas = `-- name: ListPessoasFisicas :many
SELECT id, renda_mensal, idade, nome_completo, celular, email, categoria, saldo, user_id
FROM pessoa_fisica
ORDER BY nome_completo
LIMIT $1
OFFSET $2
`

type ListPessoasFisicasParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPessoasFisicas(ctx context.Context, arg ListPessoasFisicasParams) ([]PessoaFisica, error) {
	rows, err := q.db.Query(ctx, listPessoasFisicas, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PessoaFisica
	for rows.Next() {
		var i PessoaFisica
		if err := rows.Scan(
			&i.ID,
			&i.RendaMensal,
			&i.Idade,
			&i.NomeCompleto,
			&i.Celular,
			&i.Email,
			&i.Categoria,
			&i.Saldo,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePessoaFisica = `-- name: UpdatePessoaFisica :one
UPDATE pessoa_fisica
SET
    renda_mensal = $2,
    idade = $3,
    nome_completo = $4,
    celular = $5,
    email = $6,
    categoria = $7,
    saldo = $8
WHERE id = $1
RETURNING id, renda_mensal, idade, nome_completo, celular, email, categoria, saldo, user_id
`

type UpdatePessoaFisicaParams struct {
	ID           uuid.UUID `json:"id"`
	RendaMensal  float64   `json:"renda_mensal"`
	Idade        int32     `json:"idade"`
	NomeCompleto string    `json:"nome_completo"`
	Celular      string    `json:"celular"`
	Email        string    `json:"email"`
	Categoria    string    `json:"categoria"`
	Saldo        float64   `json:"saldo"`
}

func (q *Queries) UpdatePessoaFisica(ctx context.Context, arg UpdatePessoaFisicaParams) (PessoaFisica, error) {
	row := q.db.QueryRow(ctx, updatePessoaFisica,
		arg.ID,
		arg.RendaMensal,
		arg.Idade,
		arg.NomeCompleto,
		arg.Celular,
		arg.Email,
		arg.Categoria,
		arg.Saldo,
	)
	var i PessoaFisica
	err := row.Scan(
		&i.ID,
		&i.RendaMensal,
		&i.Idade,
		&i.NomeCompleto,
		&i.Celular,
		&i.Email,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}

const updateSaldoPessoaFisica = `-- name: UpdateSaldoPessoaFisica :one
UPDATE pessoa_fisica
SET saldo = $2
WHERE id = $1
RETURNING id, renda_mensal, idade, nome_completo, celular, email, categoria, saldo, user_id
`

type UpdateSaldoPessoaFisicaParams struct {
	ID    uuid.UUID `json:"id"`
	Saldo float64   `json:"saldo"`
}

func (q *Queries) UpdateSaldoPessoaFisica(ctx context.Context, arg UpdateSaldoPessoaFisicaParams) (PessoaFisica, error) {
	row := q.db.QueryRow(ctx, updateSaldoPessoaFisica, arg.ID, arg.Saldo)
	var i PessoaFisica
	err := row.Scan(
		&i.ID,
		&i.RendaMensal,
		&i.Idade,
		&i.NomeCompleto,
		&i.Celular,
		&i.Email,
		&i.Categoria,
		&i.Saldo,
		&i.UserID,
	)
	return i, err
}
